name: Check Daggerverse Modules

on:
  schedule:
    # Runs every day at 00:00 UTC. Adjust the cron schedule according to your needs.
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  check-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
      
    - name: Run fetch_daggerverse.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python fetch_daggerverse.py

    # Add any other steps you might have, like committing changes to the repository