name: Check Daggerverse Modules

on:
  schedule:
    # Runs every day at 00:00 UTC. Adjust the cron schedule according to your needs.
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  check-modules:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch the whole repository history for commits, tags, etc.
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run fetch_daggerverse.py
      run: python fetch_daggerverse.py

    - name: Commit known_modules.txt changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add known_modules.txt
        git commit -m "Update known modules list" -a || echo "No changes to commit"
        git push
